### ISSUE TITLE
What is a web server doing in the installer?

### ISSUE THREAD

**Issue by soegaard** [nodejs/installer#57]
Why is this included in the installer?

https://github.com/nodejs/installer/blob/master/src/renderer/lib/examples.js

**Comment by ChALkeR** [comment]
@soegaard That's not a web server, that's a string with code demonstrating how to build a web server.
That code is not executed, it's shown to user as text (because it is just text).

It's used in https://github.com/nodejs/installer/blob/master/src/renderer/components/RandomExample.jsx
to show code examples, which is then shown on the right panel here:
https://github.com/nodejs/installer/blob/master/src/renderer/components/RightPanel.jsx

**Comment by ChALkeR** [comment]
Closing as answered, feel free to comment/reopen if there are more concerns about that.

**Comment by soegaard** [comment]
Yes exactly. Why is such an example in the installer?

The job of the installer is to download the zip-file, unpack it and copy the files to proper folders.
I don't see why an installer has examples of anything.

**Comment by Qard** [comment]
To be friendly and helpful for people new to Node.js. It presents a nice place for them to get started with trying it out once the install completes.

**Comment by soegaard** [comment]
That makes sense.

In my defense I never got to see what happens when the installer is finished:

https://github.com/nodejs/installer/issues/13

**Comment by addaleax** [comment]
@soegaard I don’t think this project (new installer) is going anywhere, at least until somebody picks it up again.
